"""create video translation tag tables

Revision ID: 18e286700e23
Revises: 53addd06ac1a
Create Date: 2026-05-26 16:12:39.564068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18e286700e23'
down_revision: Union[str, None] = '53addd06ac1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_translation_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_video_translation_tags_user_normalized_name')
    )
    op.create_index('ix_video_translation_tags_user_id', 'video_translation_tags', ['user_id'], unique=False)
    op.create_index('ix_video_translation_tags_user_updated_at', 'video_translation_tags', ['user_id', 'updated_at'], unique=False)
    op.create_table('video_translation_task_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['video_translation_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['video_translation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'tag_id', name='uq_video_translation_task_tags_task_tag')
    )
    op.create_index('ix_video_translation_task_tags_tag_created_at', 'video_translation_task_tags', ['tag_id', 'created_at'], unique=False)
    op.create_index('ix_video_translation_task_tags_tag_id', 'video_translation_task_tags', ['tag_id'], unique=False)
    op.create_index('ix_video_translation_task_tags_task_id', 'video_translation_task_tags', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_translation_task_tags_task_id', table_name='video_translation_task_tags')
    op.drop_index('ix_video_translation_task_tags_tag_id', table_name='video_translation_task_tags')
    op.drop_index('ix_video_translation_task_tags_tag_created_at', table_name='video_translation_task_tags')
    op.drop_table('video_translation_task_tags')
    op.drop_index('ix_video_translation_tags_user_updated_at', table_name='video_translation_tags')
    op.drop_index('ix_video_translation_tags_user_id', table_name='video_translation_tags')
    op.drop_table('video_translation_tags')
    # ### end Alembic commands ###
